[
    {
        id: 'product1',
        name: 'The Classical Music Book',
        type: 'book',
        category: 'music',
        release: '2018',
        author: `DK`,
        price: 1770,
        description: `<p><strong>About The Classical Music Book</strong></p>
        <p>From Mozart to Mendelssohn, this comprehensive guide to classical music history and classical music biography is the perfect latest addition to the bestselling Big Ideas series.</p>
        <p>Easy to understand and clear to follow, this history of classical music explores and explains music theory and the impact of seminal pieces, while also providing fascinating stories about the lives of crucial composers and performers.</p>
        <p>Including an insightful foreword by Katie Derham, The Classical Music Book analyses over 90 works by famous composers. From Thomas Tallis in the early period to baroque masters like Bach and Handel, to the classical genius of Beethoven and Wagner and beyond to the modern day, The Classical Music Book explores the key ideas underpinning the world's greatest classical compositions and musical traditions, and defines their importance to the musical canon, placing them into their wider social, cultural, and historical context.</p>
        <p>The unique approach to the subject makes this book the perfect classical music guide for everyone. Regardless of whether you are relatively new to the subject and want to learn or if you are a classical music aficionado, there is plenty to discover in The Classical Music Book.</p>`,
        image: '/vendor/img/product/book/The-Classical-Music-Book.jpg',
    },
    {
        id: 'product2',
        name: 'The Movie Book',
        type: 'book',
        category: 'movie',
        release: '2016',
        author: `DK`,
        price: 1776,
        description: `<p><strong>About The Movie Book</strong></p>
        <p>Explore the rich history of cinema like never before - from the golden age of black-and-white films to international art-house and 21st-century sci-fi - uncovering the key themes and big ideas behind more than 80 of the world's most celebrated cinematic gems.</p>
        <p>Beginning with the iconic La Voyage Dans La Lune (1902) and ending with Richard Linklater's ground-breaking Boyhood (2014), The Movie Book chronicles more than 100 of the best films ever made - from comedies and dramas, to animations, documentaries, and brings cinema to life.</p>
        <p>Discover everything about your favourite movies, as well as celebrated classics, the films you need to see, through iconic quotes and film stills, posters, biographies, movie memorabilia and narrative timelines.</p>
        <p>Essential for anyone with a passion for cinema, The Movie Book is ready for its close-up.</p>`,
        image: '/vendor/img/product/book/the_movie_book.jpg',
    },
    {
        id: 'product3',
        name: 'Guitar for Beginners: How to Play Your First Song In 7 Days Even If You have Never Picked Up A Guitar',
        type: 'book',
        category: 'music',
        author: `Guitar Head`,
        release: '2019',
        price: 1776,
        description: `<h1><strong>It Took Me 3 Months to Play My First Song - But You’ll Be Doing That in Less Than A Week.</strong></h1><p>It wasn’t because I was slow or bad at guitar.</p><p>Neither was it because I practiced less.</p><p>I was simply <strong>misguided</strong> - like every other person to ever pick up the guitar!</p><p>I took the “traditional” method of learning where you learn all the chords and all the theory behind it before you get to the fun part. This also involves <strong>months of practice</strong> and learning boring theory.</p><p>This book is here to end that - to simplify things - to make things so simple that you’ll be playing your <strong>first melody on day 1</strong> and your first song within 7 days.</p>`,
        image: '/vendor/img/product/book/guitar_for_beginners.jpg',
    },
    {
        id: 'product4',
        name: 'The Ultimate Guide to Singing: Gigs, Sound, Money and Health',
        type: 'book',
        category: 'music',
        author: `Gregory A. Barker, Kathy Alexander`,
        release: '2014',
        price: 6470,
        description: `<p>Every aspect of singing and a singing life is addressed by leading experts from across the industry - from essential aspects of vocal technique and health to choosing a mic, running a sound system, mastering vocal effects, growing a fan base and achieving unforgettable performances and recordings.</p> <ul> <li> <b>136 Music Industry Experts</b> on Every Aspect of a Singing Life </li><li> <b>Focused Actions</b> in 18 Chapters to Move Your Career Head </li><li> <b>Answers</b> to 187 REAL Questions asked by Singers</li></ul> <br> <p><b>Leading Experts Speak to Singers</b>`,
        image: '/vendor/img/product/book/the_ultimate_guide_for_singing.jpg',
    },
    {
        id: 'product5',
        name: 'Learn to Play Piano in Six Weeks or Less',
        type: 'book',
        category: 'music',
        author: `Dan Delaney, Bill Chotkowski`,
        release: '2009',
        price: 810,
        description: `<b>Wish you could sit down at the piano and effortlessly play without years of lessons? Now you can!</b> Many people wish they could sit down at the piano and simply play, their hands flying over the keys as melodies pour out. With this simple, achievable program that’s possible . . .&nbsp;<i>in just six weeks</i>. Using Dan Delaney’s innovative chord playing techniques, as opposed to more classical methods, musical newcomers and lapsed musicians can quickly and easily gain skills. Each of the six weeks’ worth of lessons contains several exercises. The classes build on each other, becoming progressively more difficult as the player’s ability improves, and every lesson includes sheet music, practice advice, and an evaluation at the end. Plus, MP3 audios of the lessons will be available for free on Delaney’s website.`,
        image: '/vendor/img/product/book/learn_to_play_piano.jpg',
    },

    {
        id: 'product6',
        name: 'The Greatest Showman',
        type: 'dvd',
        category: 'movie',
        author: `Michael Gracey`,
        actor: `Hugh Jackman, Michelle Williams, Zac Efron, Zendaya`,
        release: '2017',
        price: 1300,
        description: `<b>The Greatest Showman</b> is a 2017 American musical biographical drama film directed by Michael Gracey in his directorial debut, written by Jenny Bicks and Bill Condon and starring Hugh Jackman, Zac Efron, Michelle Williams, Rebecca Ferguson, and Zendaya. Featuring nine original songs from Benj Pasek and Justin Paul, the film is inspired by the story of P. T. Barnum's creation of Barnum's American Museum and the lives of its star attractions.`,
        image: '/vendor/img/product/movie/the_greatest_swordman.jpg',
    },
    {
        id: 'product7',
        name: 'Les Misérables',
        type: 'dvd',
        category: 'movie',
        author: `Tom Hooper`,
        actor: `Hugh Jackman, Russell Crowe, Anne Hathaway, Amanda Seyfried`,
        release: '2012',
        price: 650,
        description: `<b>Les Misérables</b> is a 2012 epic historical period musical film directed by Tom Hooper and scripted by William Nicholson, Alain Boublil, who wrote the original French lyrics, Claude-Michel Schönberg, who wrote the music, and Herbert Kretzmer, who wrote the English lyrics, based on the 1862 French novel of the same name by Victor Hugo, which also inspired a 1980 musical by Boublil and Schönberg. The film is a British and American venture distributed by Universal Pictures. The film stars an ensemble cast led by Hugh Jackman, Russell Crowe, Anne Hathaway, Eddie Redmayne, Amanda Seyfried, Helena Bonham Carter, and Sacha Baron Cohen.`,
        image: '/vendor/img/product/movie/les_miserables_.jpg',
    },
    {
        id: 'product8',
        name: 'La La Land',
        type: 'dvd',
        category: 'movie',
        author: `Damien Chazelle`,
        actor: `Ryan Gosling, Emma Stone, J. K. Simmons, John Legend và Rosemarie DeWitt`,
        release: '2016',
        price: 490,
        description: `<b>La La Land</b> is a 2016 American romantic comedy musical film written and directed by Damien Chazelle. It stars Ryan Gosling as a jazz pianist and Emma Stone as an aspiring actress, who meet and fall in love while pursuing their dreams in Los Angeles. John Legend, Rosemarie DeWitt, Finn Wittrock, and J. K. Simmons also star.`,
        image: '/vendor/img/product/movie/la_la_land.jpg',
    },
    {
        id: 'product9',
        name: 'A Star Is Born',
        type: 'dvd',
        category: 'movie',
        author: `Bradley Cooper`,
        actor: `Cooper, Lady Gaga, Dave Chappelle, Andrew Dice Clay, and Sam Elliott`,
        release: '2018',
        price: 970,
        description: `<b>A Star Is Born</b> is a 2018 American romantic musical drama film produced and directed by Bradley Cooper (in his directorial debut) and written by Cooper, Eric Roth and Will Fetters. It stars Cooper, Lady Gaga, Dave Chappelle, Andrew Dice Clay, and Sam Elliott, and follows a hard-drinking musician (Cooper) who discovers and falls in love with a young singer (Gaga). It is the third remake of the original 1937 film, after the 1954 musical and the 1976 musical.`,
        image: '/vendor/img/product/movie/a_star_is_born.jpg',
    },
    {
        id: 'product10',
        name: 'Bohemian Rhapsody',
        type: 'dvd',
        category: 'movie',
        author: `Bryan Singer`,
        actor: ` Rami Malek, Lucy Boynton, Gwilym Lee, Ben Hardy, Joe Mazzello, Aidan Gillen, Tom Hollander, Allen Leech, and Mike Myers`,
        release: '2018',
        price: 650,
        description: `<b>Bohemian Rhapsody</b> is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer[a] from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach. It stars Rami Malek as Mercury, with Lucy Boynton, Gwilym Lee, Ben Hardy, Joe Mazzello, Aidan Gillen, Tom Hollander, Allen Leech, and Mike Myers in supporting roles. Queen members Brian May and Roger Taylor served as consultants. A British-American venture, the film was produced by 20th Century Fox, Regency Enterprises, GK Films, and Queen Films, with Fox serving as distributor. The film follows the singer's life from the formation of the band up to their 1985 Live Aid performance at the original Wembley Stadium.`,
        image: '/vendor/img/product/movie/bohemian_rhapsody.jpg',
    },

    {
        id: 'product11',
        name: 'Classic Rock',
        type: 'magazine',
        category: 'music',
        author: `Future plc`,
        release: '2020',
        price: 1620,
        description: `<b>Classic Rock</b><h2>Reviews, news and features from the multi-faceted, high-octane world of rock.</h2><p>Classic Rock is a turbo-charged, rock’n’rollathon of a magazine, packed with exclusive interviews and behind-the-scenes features on the biggest names in rock music, be it the immortallised heroes of the genre or groundbreaking emerging performers. </p>`,
        image: '/vendor/img/product/magazine/classic_rock.jpg',
    },
    {
        id: 'product12',
        name: 'Guitarist',
        type: 'magazine',
        category: 'music',
        author: `Jamie Dickson`,
        release: '2020',
        price: 970,
        description: `<b>Guitarist</b><h2>Guitarist is the magazine subscription for serious players.</h2><p>Each issue is packed with the best gear reviews, in-depth interviews and pro lessons. Guitarist is a beautifully presented print and digital journal for anyone who loves making music on six strings.</p>`,
        image: '/vendor/img/product/magazine/guitarist.jpg',
    },
    {
        id: 'product13',
        name: 'Future Music',
        type: 'magazine',
        category: 'music',
        author: `Si Truss`,
        release: '2020',
        price: 970,
        description: `<b>Future Music</b><h2>Future Music delivers the technique and technology behind the hits.</h2><p>Each month, Future Music magazine is packed with inspiration for today’s modern producers. There’s reviews of the latest new gear, essential tutorials and exclusive In The Studio features where we show you how top artists create their tracks.</p>`,
        image: '/vendor/img/product/magazine/future_music.png',
    },
    {
        id: 'product14',
        name: 'BBC Music Magazine',
        type: 'magazine',
        category: 'music',
        author: `Immediate Media Company`,
        release: '2020',
        price: 4200,
        description: `<b>BBC Music Magazine</b><h2>July 2020</h2><p>In our July issue, we talk to the superstar cellist Yo-Yo Ma about the musical journeys he has taken across the world, from the Silk Road to Appalachian America. His latest project sees him returning to bluegrass music with his Goat Rodeo ensemble of musicians, all of whom we also meet in this month’s issue.</p>`,
        image: '/vendor/img/product/magazine/bbc_music_magazine.jpg',
    },
    {
        id: 'product15',
        name: 'Stereophile',
        type: 'magazine',
        category: 'music',
        author: `Avtech media americas`,
        release: '2020',
        price: 650,
        description: `<b>Stereophile</b><p>Stereophile contains in-depth reports on "high-end" loudspeakers, amplifiers, CD players, turntables and other audio components. Detailed technical measurements are also performed using the magazine's state-of-the-art test equipment.</p>`,
        image: '/vendor/img/product/magazine/stereophile.jpg',
    },

    {
        id: 'product16',
        name: 'Abbey Road',
        type: 'tape',
        category: 'music',
        author: `The Beatles`,
        release: '1969',
        price: 1295,
        description: `<b>Abbey Road</b><p>This is a cassette tape of the great Beatles album Abbey Road. The original album was released in 1969. The tape is in very good condition and plays great!</p>`,
        image: '/vendor/img/product/tape/abbey_road.jpg',
    },
    {
        id: 'product17',
        name: 'Bohemian Rhapsody',
        type: 'tape',
        category: 'music',
        author: `Freddie Mercury`,
        release: '1985',
        price: 1295,
        description: `<b>Bohemian Rhapsody</b><p>This is a cassette tape of the great Queen album Bohemian Rhapsody. The original album was released in 1985. The tape is in very good condition and plays great!</p>`,
        image: '/vendor/img/product/tape/bohemian_rhapsody.jpg',
    },
    {
        id: 'product18',
        name: 'Eagles - Their Greatest Hits',
        type: 'tape',
        category: 'music',
        author: `Eagles`,
        release: '1975',
        price: 1295,
        description: `<b>Eagles - Their Greatest Hits</b><p>This is a cassette tape of the great Eagles album about their greatest hits. The original album was released in 1975. The tape is in very good condition and plays great!</p>`,
        image: '/vendor/img/product/tape/eagles.jpg',
    },
    {
        id: 'product19',
        name: 'Guardians Of The Galaxy: Awesome Mix Vol. 1',
        type: 'tape',
        category: 'music',
        author: `David Bowie`,
        release: '1970',
        price: 1295,
        description: `<b>Guardians Of The Galaxy: Awesome Mix Vol. 1</b><p> is the collection of songs featured in the film. Music plays a major role in GUARDIANS OF THE GALAXY as the 1970s songs featured in the film are part of the storyline in a unique way. Explaining how the songs come to play in the story, director James Gunn says, 'One of the main story points in the movie is that Quill has this compilation tape (Awesome Mix #1) that he got from his mother before she died that she made for him. It was of songs that she loved, all songs from the 1970s, and that's the only thing he has left of his mother and that's the only thing he has left of his home on Earth. He uses that as a connection to his past and to the sadness that he feels of having left all that and lost all that.'
        </p>`,
        image: '/vendor/img/product/tape/guardians_of_the_galaxy_vol_1.jpg',
    },
    {
        id: 'product20',
        name: 'Guardians Of The Galaxy: Awesome Mix Vol. 1',
        type: 'tape',
        category: 'music',
        author: `David Bowie`,
        release: '1970',
        price: 1295,
        description: `<b>Guardians Of The Galaxy: Awesome Mix Vol. 1</b><p> is the collection of songs featured in the film. Music plays a major role in GUARDIANS OF THE GALAXY as the 1970s songs featured in the film are part of the storyline in a unique way. Explaining how the songs come to play in the story, director James Gunn says, 'One of the main story points in the movie is that Quill has this compilation tape (Awesome Mix #1) that he got from his mother before she died that she made for him. It was of songs that she loved, all songs from the 1970s, and that's the only thing he has left of his mother and that's the only thing he has left of his home on Earth. He uses that as a connection to his past and to the sadness that he feels of having left all that and lost all that.'
        </p>`,
        image: '/vendor/img/product/tape/guardians_of_the_galaxy_vol_1.jpg',
    },
    {
        id: 'product21',
        name: 'Abbey Road',
        type: 'cd',
        category: 'music',
        author: `The Beatles`,
        release: '1969',
        price: 450,
        description: `<b>Abbey Road</b><p> is the eleventh studio album by an english rock band The Beatles'
        </p>`,
        image: '/vendor/img/product/cd/abbey_road.jpg',
    },
    {
        id: 'product22',
        name: 'The Velvet Underground & Nico',
        type: 'cd',
        category: 'music',
        author: `The Velvet Underground, Nico`,
        release: '1967',
        price: 485,
        description: `<b>The Velvet Underground & Nico</b><p> is the debut album by American rock band the Velvet Underground, released in March 1967 by Verve Records. It was recorded in 1966 while the band were featured on Andy Warhol's Exploding Plastic Inevitable tour, which gained attention for its experimental performance sensibilities and controversial lyrical topics, including drug abuse, prostitution, sadomasochism and sexual deviancy. It sold poorly and was mostly ignored by contemporary critics, but later became regarded as one of the most influential albums in the history of popular music.
        </p>`,
        image: '/vendor/img/product/cd/the_velvet_underground_and_nico.jpg',
    },
    {
        id: 'product23',
        name: 'Pet Sounds',
        type: 'cd',
        category: 'music',
        author: `The Beach Boys`,
        release: '1966',
        price: 388,
        description: `<b>The Velvet Underground & Nico</b><p> is the 11th studio album by the American rock band the Beach Boys, released May 16, 1966 on Capitol Records. It initially met with a lukewarm critical and commercial response in the United States, peaking at number 10 on Billboard Top LPs chart, lower than the band's preceding albums. In the United Kingdom, the album was hailed by critics and peaked at number 2 in the UK Top 40 Albums Chart, remaining among the top ten positions for six months. Promoted as "the most progressive pop album ever", Pet Sounds attracted recognition for its ambitious recording and sophisticated music. It is widely considered to be among the most influential albums in the history of music.
        </p>`,
        image: '/vendor/img/product/cd/pet_sounds.jpg',
    },
    {
        id: 'product24',
        name: 'The Dark Side of the Moon',
        type: 'cd',
        category: 'music',
        author: `Pink Floyd`,
        release: '1973',
        price: 485,
        description: `<b>The Velvet Underground & Nico</b><p> is the eighth studio album by English rock band Pink Floyd, released on 1 March 1973 by Harvest Records. Primarily developed during live performances, the band premiered an early version of the record several months before recording began. New material was recorded in two sessions in 1972 and 1973 at Abbey Road Studios in London.
        </p>`,
        image: '/vendor/img/product/cd/the_dark_side_of_the_moon.jpg',
    },
    {
        id: 'product25',
        name: 'The Rise and Fall of Ziggy Stardust',
        type: 'cd',
        category: 'music',
        author: `David Bowie`,
        release: '1972',
        price: 580,
        description: `<b>The Rise and Fall of Ziggy Stardust and the Spiders from Mars</b><p> is the fifth studio album by English singer-songwriter David Bowie, released on 16 June 1972 in the United Kingdom by RCA Records. It was produced by Bowie and Ken Scott and features contributions from Bowie's backing band the Spiders from Mars – comprising Mick Ronson, Trevor Bolder and Mick Woodmansey. The album was recorded at Trident Studios in London like his previous album Hunky Dory. Most of the album was recorded in November 1971 with further sessions in January and early February 1972.
        </p>`,
        image: '/vendor/img/product/cd/the_rise_and_fall.jpg',
    },
    {
        id: 'product26',
        name: 'London Calling',
        type: 'cd',
        category: 'music',
        author: `The Clash`,
        release: '1979',
        price: 580,
        description: `<b>London Calling</b><p> London Calling is the third studio album by English rock band the Clash. It was originally released as a double album in the United Kingdom on 14 December 1979 by CBS Records, and in the United States in January 1980 by Epic Records.
        </p>`,
        image: '/vendor/img/product/cd/london_calling.jpg',
    },
    {
        id: 'product27',
        name: 'After Hours',
        type: 'cd',
        category: 'music',
        author: `The Weeknd`,
        release: '2020',
        price: 1100,
        description: `<b>After Hours</b><p> is the fourth studio album by Canadian singer The Weeknd. The album was released on March 20, 2020, by XO and Republic Records. The album was produced primarily by The Weeknd, along with a variety of high-profile producers such as DaHeala, Illangelo, Max Martin and Metro Boomin, all of whom The Weeknd had worked with previously. The standard edition has no features, although the remixes edition contains guest appearances from Chromatics and Lil Uzi Vert.</p>`,
        image: '/vendor/img/product/cd/blinding_lights.jpg',
    },
    {
        id: 'product28',
        name: 'Lover',
        author: 'Taylor Swift',
        type: 'cd',
        category: 'music',
        release: '2019',
        price: 970,
        description: `<b>Lover</b><p> is the seventh studio album by American singer-songwriter Taylor Swift. It was released on August 23, 2019, through Republic Records. As the executive producer, Swift enlisted producers Jack Antonoff, Louis Bell, Frank Dukes and Joel Little for the album. Lover is primarily a pop, synth-pop, electropop and pop rock record with a retro sensibility, encompassing diverse genres such as country, funk, dream pop, folk, rock and roll, R&B, bubblegum pop, pop punk and indie pop. Defined by Swift as "a love letter to love itself", Lover celebrates the full spectrum of love, using lighter and brighter tones, departing from the dark sounds of its predecessor, Reputation (2017). The album's music videos and art direction marked a change in Swift's visual appearance, which now embodies a summer aesthetic, consisting mostly of pastel colors.</p>`,
        image: '/vendor/img/product/cd/lover.jpg',
    },
    {
        id: 'product29',
        name: 'Chromatica',
        author: 'Lady Gaga',
        type: 'cd',
        category: 'music',
        release: '2020',
        price: 1130,
        description: `<b>Chromatica</b><p> is the sixth studio album by American singer Lady Gaga. It was released on May 29, 2020, by Streamline and Interscope Records. Originally scheduled for April 10, 2020, the album's release was delayed for seven weeks, due to the COVID-19 pandemic. Gaga and BloodPop served as the album's executive producers. Chromatica is a dance-pop, synth-pop and electropop album, incorporating elements of house, disco and many other electronic genres. Lyrically, it covers themes such as mental health, depression, loneliness, finding love through hardship, the trauma of sexual assault and self-worth, which stands in contrast with the positive and uptempo sound of the album. The album features guest vocals from Blackpink, Ariana Grande and Elton John.</p>`,
        image: '/vendor/img/product/cd/chromatica_lady_gaga.jpg',
    },
    {
        id: 'product30',
        name: 'Future Nostalgia',
        author: 'Dua Lipa',
        type: 'cd',
        category: 'music',
        release: '2020',
        price: 1130,
        description: `<b>Future Nostalgia</b><p> is the second studio album by English singer Dua Lipa, released on 27 March 2020 by Warner Records. Lipa enlisted writers and producers such as Jeff Bhasker, Ian Kirkpatrick, Stuart Price, The Monsters & Strangerz, in order to create a "nostalgic" pop and disco record with influences from dance-pop and electronic music, inspired by artists such as Kylie Minogue, Gwen Stefani, Madonna, Moloko, Jamiroquai, Blondie, Olivia Newton-John and OutKast.</p>`,
        image: '/vendor/img/product/cd/future_nostalgia.jpg',
    },
    {
        id: 'product31',
        name: 'Healing Flute: Indian & Native American Flute',
        author: `Kachina's Flute`,
        type: 'cd',
        category: 'music',
        release: '2010',
        price: 650,
        description: `<b>Healing Flute: Indian & Native American Flute</b>`,
        image: '/vendor/img/product/cd/healing_flute.jpg',
    },
    {
        id: 'product32',
        name: 'Bismillah',
        author: `Peter Cat Recording Co.`,
        type: 'cd',
        category: 'music',
        release: '2019',
        price: 650,
        description: `<b>Bismillah</b><p>A stunning mix of bossa nova, gypsy jazz and psychedelia, as if sung by Dean Martin…</p>`,
        image: '/vendor/img/product/cd/bismillah.jpg',
    },
    {
        id: 'product33',
        name: 'Shutdown',
        author: `Gully Gang, Divine, Mass Appeal`,
        type: 'cd',
        category: 'music',
        release: '2020',
        price: 650,
        description: `<b>Shutdown</b><p>The COVID-19 lockdown brought the entertainment industry almost to a standstill. However, independent music composers have been working from home and unveiling singles from time to time. Days after the partnership between Mass Appeal India and hip hop artist Divine’s Gully Gang made news, their first album <em>Shutdown</em> is out, and is a compilation of eight songs that try to dispel the lockdown blues.</p><p>According to a statement from the team, the album is a follow up to the 2019 album <em>Kohinoor </em>and inspired by the stay-at-home circumstances, it puts forth music that can be therapeutic amid the rise of the pandemic.</p>`,
        image: '/vendor/img/product/cd/shutdown.jpg',
    },
    {
        id: 'product34',
        name: 'Anand',
        author: `Rajesh Khanna, Amitabh Bachchan, Sumita Sanyal,...`,
        type: 'dvd',
        category: 'movie',
        release: '1971',
        price: 700,
        description: `<b>Anand</b><p> is a 1971 Indian Hindi-language drama film co-written and directed by Hrishikesh Mukherjee, with dialogues written by Gulzar. It stars Rajesh Khanna in the lead role, with a supporting cast including Amitabh Bachchan, Sumita Sanyal, Ramesh Deo and Seema Deo. The film won several awards, including the Filmfare Award for Best Film in 1972. In 2013, it was listed in Anupama Chopra's book 100 Films To See before You Die.</p>`,
        image: '/vendor/img/product/movie/anand.jpg',
        trailier: 'https://www.youtube.com/watch?v=MMXydylpeWs',
    },
    {
        id: 'product35',
        name: 'Mughal-E-Azam',
        author: `Prithviraj, Madhubala, Durga Khote,...`,
        type: 'dvd',
        category: 'movie',
        release: '1960',
        price: 700,
        description: `<b>Mughal-E-Azam</b><p>is a 1960 Indian epic historical drama film directed by K. Asif and produced by Shapoorji Pallonji. Starring Prithviraj Kapoor, Dilip Kumar, Madhubala and Durga Khote, it follows the love affair between Mughal Prince Salim (who went on to become Emperor Jahangir) and Anarkali, a court dancer. Salim's father, Emperor Akbar, disapproves of the relationship, which leads to a war between father and son.</p>`,
        image: '/vendor/img/product/movie/mughal_e_azam.jpg',
        trailier: 'https://www.youtube.com/watch?v=rXz_vWzMh_U',
    },
    {
        id: 'product36',
        name: 'Padosan',
        author: `Sunil Dutt, Saira Banu, Durga Mehmood,...`,
        type: 'dvd',
        category: 'movie',
        release: '1968',
        price: 700,
        description: `<b>Padosan</b><p> is a 1968 Indian Hindi-language comedy film directed by Jyoti Swaroop and produced by Mehmood, N. C. Sippy and written by Rajendra Krishan. It is a remake of the Bengali-language film Pasher Bari (1952) based on a short story of the same name by Arun Chowdhury[1][2] starring Bhanu Bandyopadhyay and Sabitri Chatterjee. The film stars Sunil Dutt and Saira Banu. Kishore Kumar, Mukri, Raj Kishore and Keshto Mukherjee played the supporting roles. Mehmood as the South Indian musician and rival to Sunil Dutt is among the highlights of the film. It was considered as one of the best comedy films made in Hindi film history. Kishore Kumar's character of a comical theater director was also well received. Indiatimes Movies ranked the film amongst the "Top 25 Must See Bollywood Films".[3] Music was composed by R.D. Burman and was a huge success. Kishore Kumar sang for himself while Manna Dey sang for Mehmood. Many of the scenes were shot in Brindavan Gardens located near the city of Mysore.</p>`,
        image: '/vendor/img/product/movie/padosan.jpg',
        trailier: 'https://www.youtube.com/watch?v=Dd4XFcKoa1M',
    },
    {
        id: 'product37',
        name: 'Sholay',
        author: `Dharmendra, Sanjeev Kumar, Hema Malini,...`,
        type: 'dvd',
        category: 'movie',
        release: '1975',
        price: 700,
        description: `<b>Sholay</b><p> is a 1975 Indian Hindustani-language action-adventure film written by Salim-Javed, directed by Ramesh Sippy, and produced by his father G. P. Sippy. The film is about two criminals, Veeru and Jai (played by Dharmendra and Amitabh Bachchan respectively), hired by a retired police officer (Sanjeev Kumar) to capture the ruthless dacoit Gabbar Singh (Amjad Khan). Hema Malini and Jaya Bhaduri also star, as Veeru and Jai's love interests, Basanti and Radha, respectively. Sholay is considered a classic and one of the best Indian films. It was ranked first in the British Film Institute's 2002 poll of "Top 10 Indian Films" of all time. In 2005, the judges of the 50th Filmfare Awards named it the Best Film of 50 Years.</p>`,
        image: '/vendor/img/product/movie/sholay.jpg',
        trailier: 'https://www.youtube.com/watch?v=zzTUvWfvlBg',
    },
    {
        id: 'product38',
        name: 'Deewaar',
        author: `Amitabh Bachchan, Shashi Kapoor, Nirupa Roy,...`,
        type: 'dvd',
        category: 'movie',
        release: '1975',
        price: 700,
        description: `<b>Deewaar</b><p> is a 1975 Indian action[4][5][6] crime drama film[7][8][9] written by Salim-Javed (Salim Khan and Javed Akhtar), directed by Yash Chopra, and starring Amitabh Bachchan, Shashi Kapoor, Nirupa Roy, Neetu Singh and Parveen Babi. Deewaar tells the story of a pair of impoverished brothers who, after their family is betrayed by the misplaced idealism of their father, struggle to survive in the slums of Bombay, and eventually find themselves on opposing sides of the law.[10][11][12] The Deewaar ("wall") of the title is the wall that has sprung up between the two brothers, drawn apart by fate and circumstances in a time of socio-political turmoil. Bachchan's character Vijay was loosely inspired by the real-life Bombay underworld gangster Haji Mastan.</p>`,
        image: '/vendor/img/product/movie/deewaar.jpg',
        trailier: 'https://www.youtube.com/watch?v=szdLyeqNY4k',
    },
    {
        id: 'product39',
        name: 'Gol Maal',
        author: `Amol Palekar, Utpal Dutt, Bindiya  Goswami,...`,
        type: 'dvd',
        category: 'movie',
        release: '1979',
        price: 700,
        description: `<b>Gol Maal</b><p> is a 1979 Indian Hindi-language comedy film directed by Hrishikesh Mukherjee and written by Rahi Masoom Raza and Sachin Bhowmick. It was produced by Mukherjee and N. C. Sippy, with music by Rahul Dev Burman. The film won several awards and was praised by critics.[1] It was the highest grossing Hindi film of 1979 and was a super hit.</p>`,
        image: '/vendor/img/product/movie/gol_maal.jpg',
        trailier: 'https://www.youtube.com/watch?v=T2y2BJH2a1w',
    },
    {
        id: 'product40',
        name: 'Gumnaam',
        author: `Nanda, Manoj Kumar, Pran,...`,
        type: 'dvd',
        category: 'movie',
        release: '1965',
        price: 700,
        description: `<b>Gumnaam</b><p> is a 1965 Bollywood thriller film, directed by Raja Nawathe and starring Manoj Kumar, Nanda, Pran, Helen, and Mehmood. The film is a loosely-inspired adaptation of the 1939 mystery novel And Then There Were None by Agatha Christie.</p>`,
        image: '/vendor/img/product/movie/gumnaam.jpg',
        trailier: 'https://www.youtube.com/watch?v=XemNT6cY8EE',
    },
    {
        id: 'product41',
        name: 'Last Dance',
        author: `Donna Summer`,
        type: 'dvd',
        category: 'music',
        release: '1978',
        price: 750,
        description: `<b>Last Dance</b><p>  is a song by American singer Donna Summer from the soundtrack album to the 1978 film Thank God It's Friday. It was written by Paul Jabara, co-produced by Summer's regular collaborator Giorgio Moroder and Bob Esty, and mixed by Grammy Award-winning producer Stephen Short, whose backing vocals are featured in the song. </p>`,
        image: '/vendor/img/product/dvd/last_dance.jpg',
    },
    {
        id: 'product42',
        name: 'More than a feeling',
        author: `Boston`,
        type: 'dvd',
        category: 'music',
        release: '1976',
        price: 800,
        description: `<b>More than a feeling</b><p> is a song by the American rock band Boston. Written by Tom Scholz, it was released as the lead single from their self-titled debut album on Epic Records in September 1976, with "Smokin'" on the b-side. The single peaked at number five on the Billboard Hot 100. The track is now a staple of classic rock, and in 1999, it was named the 39th best hard rock song of all time by VH1. It was included in the Rock and Roll Hall of Fame's list of the 500 Songs That Shaped Rock and Roll and was also ranked at Number 500 on Rolling Stone's 2004 list of the 500 Greatest Songs of All Time, though it was dropped from the 2010 update.</p>`,
        image: '/vendor/img/product/dvd/more_than_a_feeling.jpg',
    },
    {
        id: 'product43',
        name: 'Walter Egan',
        author: `Boston`,
        type: 'dvd',
        category: 'music',
        release: '1978',
        price: 400,
        description: `<b>Walter Egan</b><p>  is a hit single written and performed by Walter Egan, released in May 1978. It was the first and biggest hit on Egan's second solo LP, Not Shy. It reached number eight on the U.S. Billboard Hot 100 and number nine in Canada. It spent 22 weeks on the American charts. the United States, peaking at number 10 on Billboard Top LPs chart, lower than the band's preceding albums. </p>`,
        image: '/vendor/img/product/dvd/magnet_and_steel.jpg',
    },
    {
        id: 'product44',
        name: 'Nonsense and Lullabies: Poems for Children',
        author: `Lions Gate`,
        type: 'tape',
        category: 'poem',
        release: '1992',
        price: 1000,
        description: `<b>Nonsense and Lullabies</b><p> Chances are, if you’ve grown up reading poetry, you’ve heard a nursery rhyme or twenty. They’re catchy, easy to sing, and full of nonsense. But did you know that nursery rhymes actually have a long history, and many of them have surprising origin stories? Read on to discover the fascinating past of nursery rhymes and lullabies, and get some ideas for more rhymes to explore in your teatime!</p>`,
        image: '/vendor/img/product/tape/nonsense_and_lubbabies.jpg',
    },
    {
        id: 'product45',
        name: 'Teddy Tape: Stories, Songs and Poems',
        author: `Richard Mitchley`,
        type: 'tape',
        category: 'poem',
        release: '1994',
        price: 1000,
        description: `<b>Teddy Tape</b><p> There are all shapes and sizes of bear. There are bears that are furry and bears that have hair. This tape includes stories, songs and poems about all sorts of different bears. The tape is read by Richard Mitchley, Jill Shilling and Sharon Campbell.</p>`,
        image: '/vendor/img/product/tape/teddy_tape.jpg',
    },
    {
        id: 'product46',
        name: 'Popular English Children Rhymes',
        author: `Jukebox`,
        type: 'tape',
        category: 'poem',
        release: '2015',
        price: 1000,
        description: `<b>Popular English Children Rhymes</b></p>`,
        image: '/vendor/img/product/tape/popular_english_children.png',
    },
    {
        id: 'product47',
        name: `Baby's Morningtime`,
        author: `Judy Collins`,
        type: 'tape',
        category: 'poem',
        release: '1990',
        price: 700,
        description: `<b>Baby's Morningtime</b></p>`,
        image: '/vendor/img/product/tape/baby_morningtime.png',
    },
]